version: '3.8' 
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DB_HOST=db # El host dentro del docker-compose es el nombre del servicio
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=calculadora_db
    volumes:
      - .:/app
    networks:
      - calculadora-network
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: calculadora_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data # Persist database data
volumes:
    networks:
      - calculadora-network